import {
  BadgeCheck,
  Bell,
  BookOpen,
  ChartColumnIncreasing,
  Clock3,
  FileBadge,
  FileSearch,
  Gauge,
  History,
  LayoutDashboard,
  QrCode,
  Search,
  Settings,
  ShieldCheck,
  Upload,
  UserCircle2,
} from 'lucide-react'

export const iconMap = {
  analytics: ChartColumnIncreasing,
  badge: BadgeCheck,
  bell: Bell,
  book: BookOpen,
  clock: Clock3,
  dashboard: LayoutDashboard,
  gauge: Gauge,
  history: History,
  profile: UserCircle2,
  qr: QrCode,
  search: Search,
  settings: Settings,
  shield: ShieldCheck,
  support: FileBadge,
  upload: Upload,
  verify: FileSearch,
}
